EnterScore/Controllers/FixtureController.cs
using BusinessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace EnterScore.Controllers
{

    public class FixtureController : Controller
    {


        private readonly IFixtureService _fixtureService;

        public FixtureController(IFixtureService fixtureService)
        {
            _fixtureService = fixtureService;
        }
        //BU SAYFA BİR İŞE YARAMIYOR TÜM VERİLER SİLİNECEK
        // Ana sayfa - Tüm maçları ve haftaları gösterir
        public IActionResult Index()
        {
            var matches = _fixtureService.TGetMatchesWithTeams();
            return View(matches);
        }

        // Önceki hafta için aksiyon metodu
        public IActionResult PreviousWeek()
        {
            var matches = _fixtureService.TGetMatchesWithTeams();
            var maxWeek = matches.Max(m => m.Week);

            // Mevcut hafta numarasını al
            int currentWeek = int.Parse(HttpContext.Request.Query["currentWeek"]);

            // Şu anki haftadan 1 çıkararak önceki haftaya geç
            int previousWeek = currentWeek - 1;

            // Önceki haftayı kontrol et
            if (previousWeek >= 1)
            {
                // Önceki haftanın maçlarına ulaşmak için query string ekleyerek sayfayı yönlendir
                return RedirectToAction("Index", new { currentWeek = previousWeek });
            }
            else
            {
                // Önceki hafta 1'den küçükse ana sayfaya yönlendir
                return RedirectToAction("Index");
            }
        }

        // Sonraki hafta için aksiyon metodu
        public IActionResult NextWeek()
        {
            var matches = _fixtureService.TGetMatchesWithTeams();
            var maxWeek = matches.Max(m => m.Week);

            // Mevcut hafta numarasını al
            int currentWeek = int.Parse(HttpContext.Request.Query["currentWeek"]);

            // Şu anki haftadan 1 ekleyerek sonraki haftaya geç
            int nextWeek = currentWeek + 1;

            // Sonraki haftayı kontrol et
            if (nextWeek <= maxWeek)
            {
                // Sonraki haftanın maçlarına ulaşmak için query string ekleyerek sayfayı yönlendir
                return RedirectToAction("Index", new { currentWeek = nextWeek });
            }
            else
            {
                // Sonraki hafta mevcut haftadan büyükse, ana sayfaya yönlendir
                return RedirectToAction("Index");
            }
        }
    }
}

EnterScore/Controllers/ResultController.cs
using Microsoft.AspNetCore.Mvc;

namespace EnterScore.Controllers
{
    public class ResultController : Controller
    {
        [HttpGet]
        public IActionResult Index(int id)
        {
            TempData["id"] = id;
            return View();
        }
    }
}

EnterScore/Views/Shared/Components/_FixturePartial/Default.cshtml
@model IEnumerable<EntityLayer.Concrete.Fixture>

<div class="fixture-section">
    <div class="container">
        <div class="text-center">
            <h1>@ViewBag.CurrentPage. HAFTA</h1>
        </div>
        <div class="row inner-custom-row">
            <div class="col-md-12">
                @foreach (var item in Model)
                {
                    if (@item.Matches.Count > 0)
                    {
                        <div class="row">
                            <div class="white-match">
                                <a asp-controller="Result" asp-action="Index" asp-route-id="@item.Matches[0].MatchID">
                                    <div>
                                        <div class="col-md-4">
                                            <div class="match-left">
                                                <div class="fixture-team-img">
                                                    <img src="@item.HomeTeam.SignedUrl" width="80" height="77" alt="">
                                                </div>
                                                <div class="fixture-team-name fixture-team-left">
                                                    <h1>@item.HomeTeam.Name</h1>
                                                    <p>@item.HomeTeam.Coach.Name</p>

                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="fixture-team-date">
                                                <p>@item.Matches[0].HomeTeamGoals - @item.Matches[0].AwayTeamGoals</p>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="match-right">
                                                <div class="fixture-team-name fixture-team-right text-right">
                                                    <h1>@item.AwayTeam.Name</h1>
                                                    <p>@item.AwayTeam.Coach.Name</p>

                                                </div>
                                                <div class="fixture-team-img">
                                                    <img src="@item.AwayTeam.SignedUrl" width="80" height="77" alt="">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="row">
                            <div class="white-match">

                                <div class="col-md-4">
                                    <div class="match-left">
                                        <div class="fixture-team-img">
                                            <img src="@item.HomeTeam.SignedUrl" width="80" height="77" alt="">
                                        </div>
                                        <div class="fixture-team-name fixture-team-left">
                                            <h1>@item.HomeTeam.Name</h1>
                                            <p>@item.HomeTeam.Coach.Name</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="fixture-team-date">
                                        <p>OYNANACAK</p>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="match-right">
                                        <div class="fixture-team-name fixture-team-right text-right">
                                            <h1>@item.AwayTeam.Name</h1>
                                            <p>@item.AwayTeam.Coach.Name</p>

                                        </div>
                                        <div class="fixture-team-img">
                                            <img src="@item.AwayTeam.SignedUrl" width="80" height="77" alt="">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="d-flex justify-content-center">
            <div class="pagination-container mt-3">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(ViewBag.CurrentPage == 1 ? "disabled" : "")">
                        <a class="page-link" asp-controller="Fixture" asp-action="Index" asp-route-id="@((ViewBag.CurrentPage > 1) ? ViewBag.CurrentPage - 1 : 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for (int i = 1; i <= ViewBag.TotalPages; i++)
                    {
                        <li class="page-item @(i == ViewBag.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-controller="Fixture" asp-action="Index" asp-route-id="@i">@i</a>
                        </li>
                    }
                    <li class="page-item @(ViewBag.CurrentPage == ViewBag.TotalPages ? "disabled" : "")">
                        <a class="page-link" asp-controller="Fixture" asp-action="Index" asp-route-id="@((ViewBag.CurrentPage < ViewBag.TotalPages) ? ViewBag.CurrentPage + 1 : ViewBag.TotalPages)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>